### ISSUE TITLE
Complete PCG and Enemy+Player Development

### ISSUE THREAD

**Issue by jaf470** [PhlexPlexico/CMPT306Project#2]
I'm just going to paste what I put in the milestone here because the milestone does not recognize formatting.  Any ideas or comments can be left in this thread.

What should be completed by then:

- Rooms with slightly varying difficulty.
  * Eg. Variance of 1 to 2 difficulty levels, but after a boss fight difficulty should have a sharp drop by 4 or 5 as a "rest phase".

- Enemy and player mechanics completed
  * Enemies will probably be taken from assignment 2/3.  Player behaviour should be refined to what we want.  Eg. is it going to be a mage with one spell?

- Slight randomness to doors.
  * Some lead to dead ends.  Some are blocked (either new sprite or just remove the sprite through scripting).

- Different layouts/sizes of rooms
  * Just something so not all rooms look alike and offer something new to player experience.

There is a development freeze after this so everything needs to be completed by this milestone.  Play testing comes immediately after.

**Comment by PhlexPlexico** [comment]
PCG Has been completed to a point to close this issue. Once again see issue #9 for the last bit of the problems with PCG. Once completed, the big portion of our project will be completed. Justin you da real MVP even if you think I don't have a heart </3
