### ISSUE TITLE
Art, Sound and other Dramatic Elements

### ISSUE THREAD

**Issue by AngryShrimp** [PhlexPlexico/CMPT306Project#3]

**Comment by PhlexPlexico** [comment]
Walls = completed. Thanks Keenan!

**Comment by jaf470** [comment]
Need a locked door and key for PCG.  I'm assuming Evan needs a heart (haha) for enemy drops.

**Comment by PhlexPlexico** [comment]
I'm a monster and have no need for hearts. However, player will need a few to annotate his health to the player so we don't get confusion during play testing or alpha testing. I believe Keenan has good progress on enemies so far!

**Comment by PhlexPlexico** [comment]
Sounds still needed. Urgent since game is due in three days.
