### ISSUE TITLE
PlayerTemp needs to be removed from all scenes except Start

### ISSUE THREAD

**Issue by jaf470** [PhlexPlexico/CMPT306Project#9]
This needs to be done so dynamic values attached to the player persist and so we can change the player position in room transitions (so it doesn't spawn at the same place every scene).

**Comment by PhlexPlexico** [comment]
Removed players from first few room locally, tried moving into another room and player does not persist in game.

**Comment by PhlexPlexico** [comment]
Justin completed this. Pcg works now!
